-- Migration 002: Add flowchart_json column to papers table
-- Stores: { nodes, edges, annotations } generated by the flowchart pipeline.
-- Run with: python -m api.scripts.migrate

ALTER TABLE papers
  ADD COLUMN IF NOT EXISTS flowchart_json jsonb;
