-- Migration 004: Free trial tracking
-- Tracks anonymous trial sessions by a client-generated UUID stored in localStorage.
-- One free upload per trial_id. Signed-in users bypass this table entirely.

CREATE TABLE IF NOT EXISTS trials (
  trial_id      TEXT        PRIMARY KEY,          -- UUID generated by the browser
  uploads_used  INTEGER     NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
